### ISSUE TITLE
Install Issue on Mac

### ISSUE THREAD

**Issue by sebvg** [QuiiBz/sherif#100]
Having trouble running sherif in my monorepo after update to 1.0.1. Works fine with 1.0.0

I'm using pnpm 9.12.2, on a mac M1 processor.

Getting this error when running `pnpm install` or `pnpm dlx sherif@latest`.

`Error: Couldn't find application binary inside node_modules for darwin-x64
    at getExePath (/Users/sebastianvangerwen/Library/Caches/pnpm/dlx/l5cfu5yynbbw3f5u5rkopi4f3m/192b6be53d2-d3e2/node_modules/sherif/index.js:26:11)
    at run (/Users/sebastianvangerwen/Library/Caches/pnpm/dlx/l5cfu5yynbbw3f5u5rkopi4f3m/192b6be53d2-d3e2/node_modules/sherif/index.js:37:35)
    at Object.<anonymous> (/Users/sebastianvangerwen/Library/Caches/pnpm/dlx/l5cfu5yynbbw3f5u5rkopi4f3m/192b6be53d2-d3e2/node_modules/sherif/index.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49`

**Comment by QuiiBz** [comment]
Sorry for the delay on this issue. I cannot reproduce the error, have you tried using `npx` instead?

**Comment by QuiiBz** [comment]
Closing as no answers for several months. Please open a new issue if this is still happening!
